# Generated by Django 6.0.2 on 2026-02-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('released', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
