# Generated by Django 6.0.2 on 2026-02-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_console_genre_remove_game_rating_game_console_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
