# Generated by Django 6.0.2 on 2026-02-25 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('rawg_id', 'console', 'user'), name='unique_game_per_console_per_user'),
        ),
    ]
